### PR TITLE
Update forwardtesting-simulation.lisp

### PR DESCRIPTION
**Pull request by pierceglenn12345**
There seems to be a change in what :data-format expects to have passed to it. :bar no longer seems to be valid, so I am proposing that we change this to :prc.

### CODE REVIEW

**Review by wzrdsappr — COMMENTED** [review]
This is a portion of the code extracted from the book I have not used, hence have not tested very well.  I found major issues that just changing the specified data-format does not fix (additionally, specifying :prc format when the actual data format in the file in bar data, causes the prices to be read in incorrectly).

I am working to fix the issues.  The data now can be imported properly as PRC events.  I also corrected a few issues in the computation of future prices.  I have one more issue to fix before the forward testing simulation will run.  I am working on that now.

**Comment by wzrdsappr** [comment]
@pierceglenn12345 I've now pushed up the changes I made to fix the issues I found with the forward testing example. Let me know if you run into any more issues.  I should be able to respond faster now that I've refreshed my memory of this project (and found my GitHub credentials :D ).

**Comment by pierceglenn12345** [comment]
Thanks for the change! I plan to dedicate much more of my time to work on this. What is a good contact? I have a number of ideas I'd like to run by you. Cheers!

**Comment by wzrdsappr** [comment]
Yes, this is a good contact.

**Pull request closed without merging**
